language: node_js
node_js:
  - "8"
install:
  - npm install -g mocha
  - npm install -g babel-cli
  - npm install -g nyc
  - npm install -g coveralls 
  - npm install -g mocha-lcov-reporter 
script:
  - npm install
  - npm run build
  - npm run coveralls
cache:
  directories:
    - node_modules