/** Declaration file generated by dts-gen */
export class MyTextOutput {
    constructor(formatter: any);

    getFormatterText(text: any): any;

}

export class SimpleFormatter {
    constructor();

    getFormatterText(text: any): any;

}

export namespace SimpleFormatter {
    namespace prototype {
        function getFormatterText(text: any): any;

        namespace getFormatterText {
            const prototype: {
            };

        }

    }

}

